Feature branch
HeyItsGwen/Newsweek-Clone pull request #1
Opened 2019-11-08 21:31 UTC by HeyItsGwen

Opening a pull request to check for stickler errors

2019-11-08 23:41 UTC, suretrust requested changes
Hi @HeyItsGwen,

#### Great job thus far! :raised_hands: Just a few suggestions to wrap this up:

- [x] Please see my comments on your code.

**Large screen**
- [x] The total height of the three images and captions by the right is equal to the height of the ones on the left. Kindly fix as appropriate, refer to the images below.

![height](https://user-images.githubusercontent.com/31304943/68517406-c4928a80-0287-11ea-92e2-abecffc09a08.png)
![height2](https://user-images.githubusercontent.com/31304943/68517412-c9efd500-0287-11ea-9103-b5f1aac38a5b.png)

- [x] The navbar should be sticky. (The sticky navbar is smaller) Please refer to the image below:

![nav](https://user-images.githubusercontent.com/31304943/68517537-44205980-0288-11ea-8ef5-c230196ee541.png)

**Medium screen**

- [x] The navbar has some alignment issues and should be sticky. Please see the image below:

![nav2](https://user-images.githubusercontent.com/31304943/68517625-a1b4a600-0288-11ea-97c8-b4d3222ebe70.png)

**Small screen**
- [x] The navbar has some alignment issues and should be sticky. Please see the image below:

![nav3](https://user-images.githubusercontent.com/31304943/68517717-007a1f80-0289-11ea-8c02-ae4ce68a623b.png)

**Kindly submit for another code review once these issues have been fixed.** _Happy coding! :tada:_

2019-11-08 23:41 UTC, suretrust commented on index.html
> +  <link rel='stylesheet' href='./css/bootstrap.min.css' type='text/css'>
Using bootstrap's CDN is much better and faster. But not a deal-breaker.

2019-11-08 23:41 UTC, suretrust commented on index.html
> +        <div class='logoDiv'>'col-5 col
There's some error with this line, kindly fix.

2019-11-09 03:33 UTC, HeyItsGwen commented
Thanks, Saheed! Fixed, validated, and resubmitting 😃

2019-11-09 03:43 UTC, Redvanisation approved these changes
# Project approved ✔️ 

### Hello @HeyItsGwen  🌟 

### _Nice work on this project, it seems that you have met the requirements so I am approving your project. 👍_ 

### You may merge to master and submit a project completion form. 🚀 

### Good luck! 🍀

2019-11-09 04:00 UTC, HeyItsGwen commented
Thank you, Radouane!

2019-11-09 04:00 UTC, merged